### ISSUE TITLE
"Uncaught ReferenceError: _Ember is not defined" on 7.20.1

### ISSUE THREAD

**Issue by Leooo** [babel/ember-cli-babel#342] opened 2020-05-29 14:58 UTC
@rwjblue , a heads up that we are seeing an `Uncaught ReferenceError: _Ember is not defined` since this morning when consuming ember-cli-babel versions 7.20.1, at least in our stack - in case others have the same problem.

[EDIT: 7.20.2 seems to fix it, double-checking now]

**Comment by ASH-Bryan** [comment] 2020-05-29 15:02
We are seeing the same problem at my organization.

**Comment by ASH-Bryan** [comment] 2020-05-29 15:22
Even downgrading `ember-cli-babel` did not help us; we had to add this resolution in our `package.json`:

```json
"@babel/helper-compilation-targets": "7.9.6"
```

**Comment by Leooo** [comment] 2020-05-29 15:24
EDIT: 7.20.2 seems to fix it, double-checking now

**Comment by ASH-Bryan** [comment] 2020-05-29 15:34
@Leooo `^7.20.2` seems to fix it for us as well; just verifying on the build server.

**Comment by rwjblue** [comment] 2020-05-29 15:42
@Leooo - There have been a couple of fixes landed here for these types of errors, but I would not have suspected that 7.20.1 would have the error you reported. Can you share more information (what did the file look like, was it TS or JS, etc)? 

Mostly, I want to make sure there are / are not still issues that need to be addressed...

**Comment by ASH-Bryan** [comment] 2020-05-29 15:47
Confirmed; using version `7.20.2` has fixed the problem for us.

**Comment by rwjblue** [comment] 2020-05-29 16:11
> In the browser console after starting the ember app, we were seeing:
>
> ```
> 'Uncaught ReferenceError: _EmberObject is not defined'
> ```

Ya, but this should not have occurred at all with 7.20.1 (and the issues that triggered 7.20.2 and 7.20.3 were only affecting ember-cli-typescript users). If you have the time, can you please confirm that `yarn why ember-cli-babel` for `ember-cli-mirage` (in your snippet above) was _also_ using `7.20.1` or higher?

I suspect that you updated the version in your app, but the transitive dependencies were still either using the older versions (prior to 7.20.1) due to the way lockfiles intentionally preserve nested dependencies as much as possible.

**Comment by anand-murali** [comment] 2020-05-29 17:05
We are also facing the same issue, temporary fix is to pin babel-plugin-ember-modules-api-polyfill": "2.13.0" along with "ember-cli-babel": "7.20.1". Let me know if it works.

**Comment by rwjblue** [comment] 2020-05-29 17:52
@anand-murali - I don't understand what you mean. The others in this thread are saying that the issue is resolved with 7.20.2 (see above), are you saying that it is still an issue for you? If so, can you tell me which package/file is erroring and what `npm list ember-cli-babel`/`yarn why ember-cli-babel` reports?

**Comment by anand-murali** [comment] 2020-05-29 18:24
@rwjblue - Tried 7.20.2 and no luck with that as well. I was able to see: 

> Error: Assertion Failed: Ember.computed expects a function or an object as last argument.

Using node: 10.19.0, npm: 6.13.4, Ember: 2.15.3 and no TS

**Comment by rwjblue** [comment] 2020-05-30 14:16
@anand-murali - That error seems unrelated to transpilation.

**Comment by Leooo** [comment] 2020-05-30 14:58
so as of now there still seems to be some problems with 7.20.3, and the fix in https://github.com/babel/ember-cli-babel/issues/342#issuecomment-636082353 fixed some failing tests

**Comment by Leooo** [comment] 2020-05-30 18:42
Confirmed that adding `babel-plugin-ember-modules-api-polyfill": "2.13.0"` fixed the `_Ember is not defined` errors on some repos (bumping to ember-cli-babel 7.20.4 was not enough)

**Closed** 2020-05-30 19:21 UTC

**Comment by rwjblue** [comment] 2020-05-30 19:35
OK, thank you! Closing this issue, if folks come across this type of error again please open a new issue and let us know the output of `npm list ember-cli-babel`/ `yarn why ember-cli-babel` along with the snippet of original and transpiled file contents that are triggering errors.
