### ISSUE TITLE
hovering when lack of open curly brace

### ISSUE THREAD

**Issue by yaxinr** [babel/ember-cli-babel#439] opened 2022-03-18 13:07 UTC
`ember s` hovering when lack of open curly brace
with message `⠼ building... [Babel: wcapp > applyPatches]`
```js
import Controller from '@ember/controller'
import { action } from '@ember/object'
import { service } from '@ember/service'

export default class WorkcenterTaskController extends Controller {
  @service router
  @service webit
  @action submit(obj) {
    return this.webit
      .taskIssue(Number(this.model.id), obj.issueType.id, obj.msg)
      .then(() => //{ lack
        this.router.transitionTo('workcenter.task.index', this.model)
      }//<- error here
     )
  }
}
```

```js
    "ember-cli": "~4.2.0",
    "ember-cli-babel": "^7.26.11",

```

**Comment by Windvis** [comment] 2022-03-25 08:24
It sounds like the same issue as https://github.com/ember-cli/ember-cli/issues/9826 which is caused by the `@babel/parser` v7.17.7 release. Forcing the version to 7.17.3 or lower resolves the issue for now.

**Comment by bertdeblock** [comment] 2023-01-28 10:01
This was resolved by https://github.com/babel/broccoli-babel-transpiler/pull/212.

**Closed by bertdeblock** 2023-01-28 10:01 UTC
