### ISSUE TITLE
Babel is slowest tree

### ISSUE THREAD

**Issue by aalasolutions** [babel/ember-cli-babel#80] opened 2016-07-13 13:25 UTC
I am having trouble while using livereload for ```ember serve``` There is a component which is 2,000 lines template and 1,800 lines in JS.

Here is output for file changes

```
file changed site/components/site/carpets/neworderform-form/template.hbs - 1822 lines in this template

Build successful - 62844ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
Babel                                         | 61122ms             

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
Babel (20)                                    | 61280ms (3064 ms)   

file changed site/components/site/countries/country-form/template.hbs - 64 lines total in this template

Build successful - 1322ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
SourceMapConcat: Concat: App                  | 424ms               
SourceMapConcat: Concat: App Tests            | 77ms                

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
SourceMapConcat: Concat: App (1)              | 424ms               
Babel (20)                                    | 199ms (9 ms)        
SourceMapConcat: Concat: App Tests (1)        | 77ms   
```

I had posted a question on stackoverflow http://stackoverflow.com/questions/38070555/ember-cli-babel-is-too-slow-on-mac but there are no responses 

I am using following config

``` javascript
 babel: {
            compact: true,
            comments: false,
            includePolyfill: true
        }
```

**Comment by stefanpenner** [comment] 2016-07-13 15:31
@aalasolutions so your initial build takes 61s of babel, but rebuild takes 200ms ? What are warm build times

**Comment by aalasolutions** [comment] 2016-07-14 13:21
that 61 seconds is not the initial build, it is after I have changed the files as you can see the message, FILE CHANGED before that. so quick restart times are less. 

Any how I have noticed that my tmp folder is above 5gb, and when I cleaned it. my cold build and rebuilds both are speedy. After doing changes in my large file. it again started to get slow. and I noticed tmp folder is getting filled.

I have created an ember script to clean the tmp folder, which i run time to time to keep my tmp folder empty. I also have published that as addon now.

**Comment by stefanpenner** [comment] 2016-07-14 15:54
> Any how I have noticed that my tmp folder is above 5gb, and when I cleaned it. my cold build and rebuilds both are speedy. After doing changes in my large file. it again started to get slow. and I noticed tmp folder is getting filled.

Reproduction would be great as something is obviously going sideways as at the very least apps do not (should not) leak `tmp` files.

**Comment by aalasolutions** [comment] 2016-07-15 04:52
**Cold Build**

``` 
Build successful - 89470ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
Babel                                         | 54438ms             
Babel                                         | 6545ms              
Babel                                         | 6222ms              
JSHint app- QUnit                             | 5579ms              

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
Babel (20)                                    | 77481ms (3874 ms)   
JSHint app- QUnit (1)                         | 5579ms      
```

**Warm Build**
```

Build successful - 5099ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
Babel                                         | 446ms               
SassCompiler                                  | 372ms               

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
Babel (20)                                    | 1646ms (82 ms)      
SassCompiler (2)                              | 502ms (251 ms)      
TemplateCompiler (4)                          | 369ms (92 ms)       
```
Right now my rebuilds are quite fast, I will update this after 1 or 2 days without emptying temp folder.

**Comment by stefanpenner** [comment] 2016-07-15 05:42
@aalasolutions as requested above, please provide a reproduction or this isn't actionable.

**Comment by aalasolutions** [comment] 2016-07-15 05:47
@stefanpenner I am not understanding what do you mean by **Reproduction**

**Comment by stefanpenner** [comment] 2016-07-15 15:01
@aalasolutions I need a way to reproduce your exact issue so I can diagnose

**Comment by aalasolutions** [comment] 2016-07-15 15:21
@stefanpenner I am afraid I cant share you app right away, i might, but I need to change couple of things before I can shave in PM , but cant at the moment. 

Here is just a very recent error

```

file changed site/components/tabs-head/component.js
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (vendor & appJS)] failed with:
Error: EEXIST: file already exists, symlink '/Volumes/Work/htdocs/LP/lp2/tmp/broccoli_merge_trees-input_base_path-QXKZrk7B.tmp/0/.DS_Store' -> '/Volumes/Work/htdocs/LP/lp2/tmp/broccoli_merge_trees-output_path-2jC2Et1S.tmp/.DS_Store'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at symlink (/Volumes/Work/htdocs/LP/lp2/node_modules/symlink-or-copy/index.js:79:14)
    at symlinkOrCopySync (/Volumes/Work/htdocs/LP/lp2/node_modules/symlink-or-copy/index.js:55:5)
    at BroccoliMergeTrees.<anonymous> (/Volumes/Work/htdocs/LP/lp2/node_modules/broccoli-merge-trees/index.js:114:32)
    at Array.forEach (native)
    at BroccoliMergeTrees._applyPatch (/Volumes/Work/htdocs/LP/lp2/node_modules/broccoli-merge-trees/index.js:95:9)
    at BroccoliMergeTrees.build (/Volumes/Work/htdocs/LP/lp2/node_modules/broccoli-merge-trees/index.js:69:10)
    at /Volumes/Work/htdocs/LP/lp2/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Volumes/Work/htdocs/LP/lp2/node_modules/rsvp/dist/rsvp.js:493:16)

The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/Volumes/Work/htdocs/LP/lp2/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Volumes/Work/htdocs/LP/lp2/node_modules/broccoli-merge-trees/index.js:29:10)
    at BroccoliMergeTrees (/Volumes/Work/htdocs/LP/lp2/node_modules/broccoli-merge-trees/index.js:23:53)
    at module.exports (/Volumes/Work/htdocs/LP/lp2/node_modules/ember-cli/lib/broccoli/merge-trees.js:8:14)
    at EmberApp.javascript (/Volumes/Work/htdocs/LP/lp2/node_modules/ember-cli/lib/broccoli/ember-app.js:1199:10)
    at EmberApp.toArray (/Volumes/Work/htdocs/LP/lp2/node_modules/ember-cli/lib/broccoli/ember-app.js:1542:10)
    at EmberApp.toTree (/Volumes/Work/htdocs/LP/lp2/node_modules/ember-cli/lib/broccoli/ember-app.js:1564:30)
    at module.exports (/Volumes/Work/htdocs/LP/lp2/ember-cli-build.js:42:16)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Volumes/Work/htdocs/LP/lp2/node_modules/ember-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Volumes/Work/htdocs/LP/lp2/node_modules/ember-cli/lib/models/builder.js:89:10)

```

Apart from that I need to discuss this with my manager before i can share. Thanks for your time

**Comment by stefanpenner** [comment] 2016-07-15 16:14
@aalasolutions if it works, you can also share privately with just me. That would be more the sufficient for me to see if this is a new issue, or something already known.

**Comment by aalasolutions** [comment] 2016-07-18 06:29
@stefanpenner I have sent you an emaill.

**Comment by stefanpenner** [comment] 2016-07-18 15:05
@aalasolutions awesome thanks, unfortunately I haven't seen the message (it may have gotten spam filtered by google) should I expect the sender email to be the same as your github profile?

**Comment by aalasolutions** [comment] 2016-07-18 15:17
@stefanpenner I have sent it from aamir@aalasolutions.com (hosted on gmail) and sent it to your stefan.penner@gmail.com account. 

I have just sent the code, run npm install and bower install :smile: I know you know this.

**Comment by stv8** [comment] 2016-08-16 18:48
I am also experiencing this, here is an example of a cold boot. 

```
Build successful - 63231ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
Babel                                         | 23104ms
Babel                                         | 19902ms
Babel                                         | 10723ms
Babel                                         | 5115ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
Babel (20)                                    | 59772ms (2988 ms)
```


One thing I noticed is that I started getting these warnings in the output recently.

`[BABEL] Note: The code generator has deoptimised the styling of...`

I used to not get those. I tried toggling `compact` every which way but that didn't help. 

I am using  

```
ember-cli: 2.7.0
node: 6.0.0
os: darwin x64
```

And here are my dependencies

```
"devDependencies": {
    "broccoli-asset-rev": "^2.4.2",
    "broccoli-static-compiler": "^0.2.2",
    "ember-cli": "2.7.0",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-blanket": "0.9.4",
    "ember-cli-bootstrap-4": "0.0.2",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-font-awesome": "1.4.0",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-page-object": "1.3.0",
    "ember-cli-pretender": "0.6.0",
    "ember-cli-qunit": "^1.4.0",
    "ember-cli-release": "0.2.8",
    "ember-cli-sass": "5.4.0",
    "ember-cli-sass-pods": "1.2.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.4.2",
    "ember-exam": "^0.2.1",
    "ember-export-application-global": "^1.0.5",
    "ember-load-initializers": "^0.5.1",
    "ember-pdfjs": ">= 0.2.5",
    "ember-resolver": "^2.0.3",
    "loader.js": "^4.0.1"
  },
  "dependencies": {
    "ally.js": "^1.0.1",
    "body-parser": "^1.14.2",
    "ember-pdfjs": ">= 0.2.5",
    "ember-simple-auth": "1.0.1",
    "ember-uri-shim": "^0.1.0",
    "express": "^4.13.3",
    "knex": "^0.10.0",
    "liquid-fire": "0.22.1",
    "pg": "^4.5.2"
  }
```

**Comment by stefanpenner** [comment] 2016-08-16 19:16
@stv8 how many files are you babeling? What is warm boot times, what are rebuild times?

**Comment by stv8** [comment] 2016-08-16 19:32
@stefanpenner what is the best way to find how many files? Do I include `node_modules`?

Here is a warm boot and rebuild

```
Build successful - 64075ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
Babel                                         | 23637ms
Babel                                         | 20466ms
Babel                                         | 10997ms
Babel                                         | 4995ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
Babel (20)                                    | 61092ms (3054 ms)

file changed templates/index.hbs

Build successful - 1016ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
SourceMapConcat: Concat: App                  | 186ms
Babel                                         | 88ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
StaticCompiler (25)                           | 293ms (11 ms)
SourceMapConcat: Concat: App (1)              | 186ms
Babel (20)                                    | 164ms (8 ms)
```

**Comment by stefanpenner** [comment] 2016-08-17 00:28
those build times seems more or less expected, for cold boot and rebuild times, babel is slow.

**Comment by stv8** [comment] 2016-08-17 14:58
@stefanpenner Okay gotcha, but what about the warm boot above? It consistently takes an average of 60 seconds. It becomes quite painful when running tests :p

**Comment by stefanpenner** [comment] 2016-08-17 15:45
@stv8 that does not seems correct, it seems like something upstream of your babel transpiler is making changes that prevent babel from resuming quickly?

My guess is it should be like 5s -> 10s for a warm boot if the "resume" works correctly.

@stv8 is this a recent change or has "warm boot" always been crappy?

**Comment by rwjblue** [comment] 2016-08-17 15:51
Are there any warnings printed to the console?  There have been recent changes that would prevent caching across a restart, but they would all include console output indicating that something needs to be updated.

**Comment by stv8** [comment] 2016-08-17 16:53
@stefanpenner it seems like it has been a recent change, I wasn't experiencing this until I wiped my node and bower modules a few days ago. I wish I had a snapshot of the versions but my guess is that something updated and it is affecting my build. 

@rwjblue here is my output when running `ember serve`, this is a warm boot
https://gist.github.com/stv8/41f4e9df5b84050366a53bf38e58dddb

**Comment by rwjblue** [comment] 2016-08-17 17:26
These seem pretty fishy to me. 

```
[BABEL] Note: The code generator has deoptimised the styling of "nimbus/assets/pdf.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "nimbus/assets/pdf.worker.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "nimbus/templates/assets/pdf.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "nimbus/templates/assets/pdf.worker.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "nimbus/tests/assets/pdf.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "nimbus/tests/assets/pdf.worker.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "assets/pdf.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "assets/pdf.worker.js" as it exceeds the max of "100KB".
```

It is inferring that you have a `pdf.js` and `pdf.worker.js` in your projects `app` tree (otherwise babel wouldn't be running on it in general).

**Comment by stv8** [comment] 2016-08-17 19:23
@rwjblue we are using it with the `ember-pdfjs` add on, would that be why it includes it in the app tree?

**Comment by stv8** [comment] 2016-08-17 20:08
@rwjblue  I created a fresh ember app and added ember-pdfjs. 

The cold boot took ~60 secs and showed the above babel output, however the subsequent warm boots were significantly faster, taking only 2 seconds and not showing the babel output. 

I am not sure what this indicates about the build process of my original app and how it has deviated from the fresh one.

**Comment by stv8** [comment] 2016-08-17 20:47
@rwjblue I found the problem, and for anyone else who may run into it, it turns out to be an older version of liquid fire. Specifically due to these lines in the output.

https://gist.github.com/stv8/41f4e9df5b84050366a53bf38e58dddb#file-ember-server-output-L11-L12

**Comment by stefanpenner** [comment] 2016-08-17 22:18
@stv8 yup that is what we thought. Going to close this, as that "regression" is actually catching more places where the warm cache was not safe to use. If those deprecations are fixed not only should the build performance be restored but the caching will work correctly.

**Closed by stefanpenner** 2016-08-17 22:18 UTC

**Comment by aalasolutions** [comment] 2016-10-15 12:39
@stefanpenner I am back for the same issue. 

Here are my build times

`
file added site\components\site\carpets\neworderform-form\template.hbs___jb_tmp___
file changed site\components\site\carpets\neworderform-form\template.hbs___jb_tmp___
file deleted site\components\site\carpets\neworderform-form\template.hbs___jb_tmp___
file changed site\components\site\carpets\neworderform-form\template.hbs

Build successful - 100820ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
Babel                                         | 95629ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
Babel (28)                                    | 96269ms (3438 ms)`

and after few changes it goes to

`file changed site\components\site\carpets\neworderform-form\template.hbs

Build successful - 107532ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
Babel                                         | 101065ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
Babel (28)                                    | 101905ms (3639 ms)`


This slowness only occurs when I am editing this file "site\components\site\carpets\neworderform-form\template.hbs" on any other change everything works as expected. I hope you still have my source code, just change few lines and see what are the build times for you. I am doing some rearrangements of the layout structure

**Comment by aalasolutions** [comment] 2016-11-09 08:34
Hi, I am adding DEBUG=babel* details below for slowness

```
$ DEBUG=babel* ember s
version: 2.4.2
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Parse start +0ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Parse stop +587ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Start set AST +2ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: End set AST +1s
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Start module formatter init +1ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: End module formatter init +3ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Start transformer htmlbars-inline-precompile +2ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Finish transformer htmlbars-inline-precompile +350ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Start transformer builtin-pre +1ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Finish transformer builtin-pre +396ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Start transformer builtin-basic +2ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Finish transformer builtin-basic +428ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Start transformer builtin-advanced +1ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Finish transformer builtin-advanced +298ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Start transformer builtin-modules +2ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Finish transformer builtin-modules +771ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Start transformer builtin-trailing +2ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Finish transformer builtin-trailing +1s
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Generation start +2ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Generation end +3m

site/components/site/carpets/neworderform-form/component.js: line 824, col 25, 'refCarpetPND' is defined but never used.

1 error

===== 1 JSHint Error


Build successful - 184186ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
Babel                                         | 165556ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
Babel (29)                                    | 170778ms (5888 ms)

file added site\components\site\carpets\neworderform-form\template.hbs___jb_tmp___
file changed site\components\site\carpets\neworderform-form\template.hbs___jb_tmp___
file deleted site\components\site\carpets\neworderform-form\template.hbs
file deleted site\components\site\carpets\neworderform-form\template.hbs___jb_tmp___
file added site\components\site\carpets\neworderform-form\template.hbs
file added site\components\site\colors\colors-form\template.hbs___jb_tmp___
file changed site\components\site\colors\colors-form\template.hbs___jb_tmp___
file deleted site\components\site\colors\colors-form\template.hbs___jb_tmp___
file changed site\components\site\colors\colors-form\template.hbs
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Parse start +51s
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Parse stop +585ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Start set AST +2ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: End set AST +968ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Start module formatter init +1ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: End module formatter init +3ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Start transformer htmlbars-inline-precompile +1ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Finish transformer htmlbars-inline-precompile +260ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Start transformer builtin-pre +1ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Finish transformer builtin-pre +351ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Start transformer builtin-basic +2ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Finish transformer builtin-basic +408ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Start transformer builtin-advanced +2ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Finish transformer builtin-advanced +274ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Start transformer builtin-modules +1ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Finish transformer builtin-modules +717ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Start transformer builtin-trailing +1ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Finish transformer builtin-trailing +1s
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Generation start +1ms
  babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Generation end +2m
  babel [BABEL] lp2/site/components/site/colors/colors-form/template.js: Parse start +83ms
  babel [BABEL] lp2/site/components/site/colors/colors-form/template.js: Parse stop +34ms
  babel [BABEL] lp2/site/components/site/colors/colors-form/template.js: Start set AST +1ms
  babel [BABEL] lp2/site/components/site/colors/colors-form/template.js: End set AST +88ms
  babel [BABEL] lp2/site/components/site/colors/colors-form/template.js: Start module formatter init +1ms
  babel [BABEL] lp2/site/components/site/colors/colors-form/template.js: End module formatter init +3ms
  babel [BABEL] lp2/site/components/site/colors/colors-form/template.js: Start transformer htmlbars-inline-precompile +2ms
  babel [BABEL] lp2/site/components/site/colors/colors-form/template.js: Finish transformer htmlbars-inline-precompile +23ms
  babel [BABEL] lp2/site/components/site/colors/colors-form/template.js: Start transformer builtin-pre +1ms
  babel [BABEL] lp2/site/components/site/colors/colors-form/template.js: Finish transformer builtin-pre +32ms
  babel [BABEL] lp2/site/components/site/colors/colors-form/template.js: Start transformer builtin-basic +2ms
  babel [BABEL] lp2/site/components/site/colors/colors-form/template.js: Finish transformer builtin-basic +59ms
  babel [BABEL] lp2/site/components/site/colors/colors-form/template.js: Start transformer builtin-advanced +1ms
  babel [BABEL] lp2/site/components/site/colors/colors-form/template.js: Finish transformer builtin-advanced +29ms
  babel [BABEL] lp2/site/components/site/colors/colors-form/template.js: Start transformer builtin-modules +1ms
  babel [BABEL] lp2/site/components/site/colors/colors-form/template.js: Finish transformer builtin-modules +68ms
  babel [BABEL] lp2/site/components/site/colors/colors-form/template.js: Start transformer builtin-trailing +2ms
  babel [BABEL] lp2/site/components/site/colors/colors-form/template.js: Finish transformer builtin-trailing +111ms
  babel [BABEL] lp2/site/components/site/colors/colors-form/template.js: Generation start +0ms
  babel [BABEL] lp2/site/components/site/colors/colors-form/template.js: Generation end +346ms

Build successful - 143757ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
Babel                                         | 138196ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
Babel (29)                                    | 138958ms (4791 ms)
```

**Comment by aalasolutions** [comment] 2016-11-09 08:50
Now i have used

`DEBUG=* DEBUG_LEVEL=debug ember s` and there is nothing between ... so what can i do now???

```
 babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Generation start +2ms
 babel [BABEL] lp2/site/components/site/carpets/neworderform-form/template.js: Generation end +2m
```
